menu:
    Home: /
    Archives: /archives


# Read More text
excerpt_link: Read More

# Disqus Comments Shortname
disqus_shortname: lucas-inacio-github-io

# Widgets List
widgets:
  about: This is the place where I share ideas and fun projects.
  tags: true