menu:
    Home: /
    Archives: /archives


# Read More text
excerpt_link: Read More

# Disqus Comments Shortname
disqus_shortname: lucas-inacio-github-io

# Widgets List
widgets:
  about: This blog is based off the official bootstrap blog template. Checkout the corresponding tutorial at <a href="http://www.codeblocq.com">http://www.codeblocq.com</a
  tags: true