menu:
    Home: /
    Archives: /archives
    GitHub: https://github.com/lucas-inacio
    
    
# Read More text
excerpt_link: Read More

# Disqus Comments Shortname
disqus_shortname: lucas-inacio-github-io

# Widgets List
widgets:
    about: 
        title: About
        text: This is the place where I share ideas and fun projects.
    tags:
        title: Tags